[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "wpsrt"
version = "2.0.2"
description = ""
authors = ["jpk <jpk@goatpr0n.de>"]

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.8"
pillow = "^11.0.0"
enlighten = "^1.13.0"

[tool.poetry.scripts]
wpsrt = "wpsrt.cli:sort"
